# @baseUrl = http://localhost:8080
@baseUrl = https://jago-golang-task-1-production.up.railway.app

### =========================
### Check health
### =========================
GET {{baseUrl}}/health
Accept: application/json

### =========================
### Get categories
### =========================
GET {{baseUrl}}/api/categories
Accept: application/json

### =========================
### Post new categories
### =========================
POST {{baseUrl}}/api/categories
Accept: application/json
Content-Type: application/json

{
    "name": "Snacks",
    "description": "This is snacks"
}

### =========================
### Get category detail by ID
### =========================
GET {{baseUrl}}/api/categories/90b90fb7-de05-4e65-8f63-e4c235cb8014
Accept: application/json

### =========================
### Delete category by ID
### =========================
DELETE {{baseUrl}}/api/categories/90b90fb7-de05-4e65-8f63-e4c235cb8014
Accept: application/json

### =========================
### Edit category by id
### =========================
PUT {{baseUrl}}/api/categories/41b2d9d0-bd61-424c-92a4-20698577f036
Accept: application/json
Content-Type: application/json

{
    "name": "Bread",
    "description": "This is bread"
}