@baseUrl = http://localhost:8080

### =========================
### Check health
### =========================
GET {{baseUrl}}/health
Accept: application/json

### =========================
### Get products
### =========================
GET {{baseUrl}}/api/products
Accept: application/json

### =========================
### Post new product
### =========================
POST {{baseUrl}}/api/products
Accept: application/json
Content-Type: application/json

{
    "name": "FitBar",
    "stock": 100,
    "price": 2000
}

### =========================
### Get product detail by ID
### =========================
GET {{baseUrl}}/api/products/70be36fd-b5de-4bc1-94fd-a2da4fbc8e13
Accept: application/json

### =========================
### Delete product by ID
### =========================
DELETE {{baseUrl}}/api/products/70be36fd-b5de-4bc1-94fd-a2da4fbc8e13
Accept: application/json

### =========================
### Edit product by id
### =========================
PUT {{baseUrl}}/api/products/70be36fd-b5de-4bc1-94fd-a2da4fbc8e13
Accept: application/json
Content-Type: application/json

{
    "name": "FitBar Edit",
    "stock": 50,
    "price": 1000,
    "category_id": "41b2d9d0-bd61-424c-92a4-20698577f036"
}